- react-front/public/components/App.js
- react-front/public/components/Panel.js
Background: We have data! Clicking request button shows selected data for device 9.
Summary: 
- Cleans up code 
- Updates state with the API response
- Passes responseData fron App to Panel
- renders selected (random bits: id, hostname, description, device_type, last_seen, management_ip) data from response object 
- console.logs to follow process
Next steps: 
- get bigger list with more devices
- better display of data (headers for context and other things from mock up)
> Renders requested API data (device #9) in Panel component

- react-front/public/components/App.js
- react-front/public/components/Panel.js
- react-front/public/styles/main.css
Background: The request has been changed to request all devices in the API
Summary: 
- Updates the fetch URL to all devices 
- Changes unordered list element into table due to the structure of data (started aiming for columns in the mockup)
- ID in the table only because it looked like all devices had that info for sure
Next steps: 
- Give the table headers functionality to create more detailed requests (filer and such)
- Lets discuss how to move forward on Monday
> Renders request for all devices

- react-front/public/components/App.js
- react-front/public/components/DeviceList.js
- react-front/public/components/Panel.js
- react-front/public/components/Workflow.js
- react-front/public/styles/main.css
**Background**: After successfully getting device data from the API, we now focus on the Workflow interface. This requires refactoring the structure of the current code. 
**Summary**:
- I have split out the device list code into its own component `DeviceList.js` and made the naming of the data passed from `App.js` more specific to devices
- I have prepared a new `Workflow.js` component in which I will start development of the workflow interface
- Both `DeviceList` and `Workflow` components are displayed in `Panel.js`
**Next step**: 
- Comment out `DeviceList.js` code for now
- Build the four boxes in `Workflow.js`
> Prepares Panel.js to display different child components.

- react-front/public/components/DeviceList.js
- react-front/public/components/Panel.js
- react-front/public/components/Workflow.js
- react-front/public/styles/main.css
**Background**: Workflow page starts with some basic structure. 
**Summary**: 
- I have built the basic DOM elements for the work flow
- :warning: No elements have any functionality
- :warning: Close button to collapse each workflow step is not intended to be text
- :warning: DeviceList has just been comment out so it doesn't render (its not possible to navigate to it via the UI)
**Next steps**:
- add functionality!
- specifically add request button to step 2 - to ensure it works
- if time, add request button to step 1 - to ensure it works
> Adds basic structure for workflow 

- react-front/public/components/DeviceList.js
- react-front/public/components/Panel.js
- react-front/public/components/Workflow.js
- react-front/public/styles/main.css
**Background**: Workflow functionality added in bits: Step 1 
**Summary**:
- I have added the two repo buttons
- First does GET request to get commit 
- Second does PUT request to get lastest commit
**Next steps**:
- Add functionality for step 2
- Refactor workflow steps into separate child components to break up code
- Refactor requests/response status check functionality into separate files (new utils folder)
> Adds step 1 of Workflow functionality: Refresh repos

- react-front/public/components/DeviceList.js
- react-front/public/components/Panel.js
- react-front/public/components/Workflow.js
- react-front/public/components/Workflow_step1.js
- react-front/public/components/Workflow_step2.js
- react-front/public/styles/main.css
**Background**: Looks the same and works the same as PR #6, but worlkflow code split into child components according to step
**Summary**: 
- Created two new components `Workflow_step1.js` and  `Workflow_step2.js` to hold teh two separate steps
**Next steps**: 
- Start working on functionality for step 2 (continuous request and progressbar func)
- Potentially Step 3 has to be contained within the Step 2 component or be a child of it (if tehy need to access the same data)
- I'd like to try to separate the requests and status check  into their own files to not have to repeat the requests in every component
> Refactor: splits Workflow component into separate children 

- react-front/package.json
- react-front/public/components/App.js
- react-front/public/components/DeviceList.js
- react-front/public/components/Header.js
- react-front/public/components/Panel.js
- react-front/public/components/Workflow.js
- react-front/public/components/Workflow_step1.js
- react-front/public/components/Workflow_step2.js
- react-front/public/styles/main.css
**Background**: The header nav now allows navigating to Devices or Workflow pages  
Summary: 
- installed 2 dev dependencies [react-router-dom](https://www.npmjs.com/package/react-router-dom) and [history](https://www.npmjs.com/package/history) for routing
- home ('/') renders the `DeviceList.js` component
- '/workflow' renders `Workflow.js` component
- some quick styling added to show on what page you are
- I also had to move the devices API call from `App.js` to `DeviceList.js` where it belongs
> Adds routing to header nav to allow rendering of different pages

- react-front/public/components/DeviceList.js
- react-front/public/components/Workflow_step1.js
- react-front/public/components/Workflow_step2.js
- react-front/public/utils/checkResponseStatus.js
**Background**: The repeating response status check code has been removed from the components and split into separate file.
Summary: 
- statusCheck() moved to utils folder
- function imported into components
> Adds statusCheck function as separate file

- react-front/public/components/DeviceInitForm.js
- react-front/public/components/DeviceList.js
- react-front/public/styles/main.css
1. Add ability to expand device details when clicking on a row in the table of devices
2. Add form for starting device initialization from the expanded device details
3. Add some icons
4. Add pagination system at the bottom (10 results per page)
5. Messed up the CSS because I don't know what I'm doing
> Device list expand

- react-front/public/components/DeviceList.js
- react-front/public/components/Workflow_step1.js
- react-front/public/utils/checkResponseStatus.js
- react-front/public/utils/getData.js
- react-front/public/utils/sendData.js
**Background**: Repeating requests in each component results in a lot of extra code and introduced errors. Splitting the requests out in separate files allows us to reuse function that we know work.
Summary: 
- I have added getData (GET) and sendData (PUT, POST) files to the /utils
- I have imported the `checkResponseStatus()` function to the files 
- I have imported the correct requests in the `<DevicesList />` and `<Workflow_step1/>`
> Adds fetch requests in separate files

- react-front/public/components/ConfigChange/ConfigChange.js
- react-front/public/components/ConfigChange/ConfigChangeProgressBar.js
- react-front/public/components/ConfigChange/ConfigChangeStep2.js
- react-front/public/components/ConfigChange/ConfigChangeStep3.js
- react-front/public/components/ConfigChange/ConfigChangeStep4.js
- react-front/public/components/ConfigChange/DeviceFailList.js
- react-front/public/components/ConfigChange/ProgressBar.js
- react-front/public/styles/main.css
**Background**: Step 4 uses the initial API call but POSTs a `dry_run: false` data.
**Summary**: 
- I have added a button to the component and access to the API call in the parent `ConfigChange`
- I have added the relevant data to the `dataToSend` variable, but commented it out in favour of a console log until you're ready to run it for real
> Adds functionality to ConfigChangeStep4

- react-front/package-lock.json
- react-front/package.json
- react-front/public/components/Header.js
- react-front/public/components/LoginForm.js
- react-front/public/components/Panel.js
**Summary**:  
- LoginForm.js: I have added a basic login form that console logs its input and send it to the parent `Panel.js`
- Panel.js:  The email and password are used in the `login()` function which is a POST to the auth server (the request is there, but I was not able to return a token)
---
- Mock navigation: I have put login in the nav so it can be easily found
- Mock token in local storage: I have used the hardcoded token as if it came from the server and made it save in the browsers local storage
- Mock toggle of login/logout: To be able to do both login and logout (and see that token is saved/removed in local storage) I just made the login form disappear when you click login and display the login button. And reverse when login button is clicked.  
> before token to local …
> Adds start to login form

- public/components/DeviceList.js
- public/components/DeviceSearchForm.js
- public/components/Panel.js
Show information about infrastructure connections, but not all interfaces (leave it to NAV UI)
> Show links to MLAG peer and uplink peer from device details

- public/components/DeviceList.js
- public/styles/main.css
Move sync link to actions menu, add options to update facts and make device managed or unmanaged
> Add actions menu to device details

- public/components/ConfigChange/ConfigChange.js
- public/components/ConfigChange/ConfigChangeStep4.js
- public/components/ConfigChange/DryRun/DryRun.js
- public/components/ConfigChange/DryRun/DryRunProgressInfo.js
Fix issues with tailing logoutput on config change steps, should be more robust and also work better in firefox now
> Bugfix.loglines configchange share

- public/components/ConfigChange/ConfigChange.js
- public/components/ConfigChange/ConfigChangeStep1.js
- public/components/ConfigChange/DryRun/DryRunProgressBar.js
- public/components/FirmwareUpgrade/FirmwareProgressBar.js
- public/components/FirmwareUpgrade/FirmwareStep1.js
- public/components/ProgressBar.js
- public/styles/main.css
- public/utils/sendData.js
Better progress bar that shows when things fail etc, better error messages
> Feature.configchange errorimprovements

- public/components/DeviceList.js
- public/components/DeviceSearchForm.js
Also scroll up to top of page and close expanded rows.
> After making a new search, make sure to reset to first page of results

- public/components/DeviceList.js
- public/styles/main.css
Options for how to display the device list:
> Feature.devicelist extra col

- public/components/ConfigChange/ConfigChange.js
- public/components/ConfigChange/ConfigChangeStep4.js
- public/components/ConfigChange/DryRun/DryRunProgressBar.js
- public/components/ConfigChange/DryRun/DryRunProgressInfo.js
- public/components/ProgressBar.js
Add dropdown to select commit confirm type for a commit job, add dual progress bars etc for mode 2 with separate confirm job
> Feature.confirm job status

- public/components/InterfaceConfig/InterfaceConfig.js
Options for untagged vlan on trunk, aggregate id and bpdu_filter
> Feature.untagged vlan

- public/components/InterfaceConfig/InterfaceConfig.js
make sure field default values are kept even when fields are first hidden and then made visible again. make code generic for all fields
> make sure field default values are kept even when fields hidden/shown

- public/utils/getData.js
This fix is to workaround strict Azure implementation which does not allow undefined Authorization headers.
> fix getdata to handle credential undefined

- package-lock.json
- package.json
> Revert "Bump socket.io-parser and socket.io-client"

- public/components/Callback.js
- public/contexts/AuthTokenContext.js
Bugfix get username with apicall if not in token and bugfix makes sure permissions are loaded before forwarding the  user.
> 2 bugfixes, username and premissions

- public/components/DeviceList/DeviceInfoBlock.js
- public/components/DeviceList/DeviceList.js
- public/components/Header/JwtInfo.js
- public/components/InterfaceConfig/InterfaceConfig.js
- public/components/Panel.js
- public/components/Settings.js
- public/utils/getData.js
> Feature.netbox model info

- public/components/DeviceList/DeviceInfoBlock.js
- public/components/DeviceList/DeviceList.js
... and print on deviceinfo block
> Get information from netbox about status and location 

- public/components/ConfigChange/ConfigChange.js
- public/components/DeviceList/DeviceInfoBlock.js
- public/components/InterfaceConfig/InterfaceConfig.js
- public/styles/main.css
add link to monitoring/nav if netbox state is active
new way of doing tagged/untagged vlans on interface config page
> Feature access downlink nonredundant, nav link, tag/untagged toggle

- public/components/InterfaceConfig/InterfaceConfig.js
- public/components/InterfaceConfig/LldpNeighborPopup.js
- public/components/InterfaceConfig/NetboxDevice.js
- public/components/InterfaceConfig/NetboxInterfacePopup.js
> Add popups with info about netbox interface/cable and/or LLDP neighbors
